import { writeFileSync } from 'node:fs';
import { test } from '@playwright/test';
import { PHOTO, createWeddingPlan, freshApp, openFunction } from './helpers';
const OUT = process.env.SHOTS!;
test.skip(!OUT, 'screenshots only on demand');
test('screens', async ({ page }) => {
  await freshApp(page);
  await page.screenshot({ path: `${OUT}/1-home.png`, fullPage: true });
  await page.getByRole('link', { name: 'Start a plan' }).click();
  await page.screenshot({ path: `${OUT}/2-setup.png` });
  await page.goto('./#/');
  await createWeddingPlan(page);
  await openFunction(page, 'Mehendi');
  await page.getByRole('button', { name: 'Add to Main outfit' }).click();
  await page.getByLabel('Choose from photo library').setInputFiles(PHOTO);
  await page.screenshot({ path: `${OUT}/3-saved.png` });
  await page.getByRole('button', { name: 'Done' }).click();
  await page.getByRole('button', { name: /Tap to pick/ }).click();
  await page.getByRole('button', { name: 'Add to Footwear' }).click();
  await page.getByLabel('Product link').fill('https://www.amazon.in/Fizzy-Goblet-Juttis/dp/B0C1');
  await page.getByRole('button', { name: 'Save' }).first().click();
  await page.getByRole('button', { name: 'Done' }).click();
  await page.screenshot({ path: `${OUT}/4-function.png`, fullPage: true });
  await page.goto(page.url().replace(/\/f\/.*/, ''));
  await page.screenshot({ path: `${OUT}/5-overview.png`, fullPage: true });
  await page.getByRole('button', { name: 'Share', exact: true }).click();
  await page.getByRole('button', { name: /^Send 6 images$/ }).waitFor({ timeout: 20000 });
  await page.waitForTimeout(500);
  await page.screenshot({ path: `${OUT}/6-share.png` });
  const src = await page.locator('.preview img').nth(1).getAttribute('src');
  const b64 = await page.evaluate(async (u) => {
    const r = await fetch(u!); const b = await r.blob(); const buf = new Uint8Array(await b.arrayBuffer());
    let s = ''; buf.forEach((x) => (s += String.fromCharCode(x))); return btoa(s);
  }, src);
  writeFileSync(`${OUT}/7-share-image.png`, Buffer.from(b64, 'base64'));
  const src0 = await page.locator('.preview img').nth(0).getAttribute('src');
  const b640 = await page.evaluate(async (u) => {
    const r = await fetch(u!); const b = await r.blob(); const buf = new Uint8Array(await b.arrayBuffer());
    let s = ''; buf.forEach((x) => (s += String.fromCharCode(x))); return btoa(s);
  }, src0);
  writeFileSync(`${OUT}/8-overview-image.png`, Buffer.from(b640, 'base64'));
  await page.keyboard.press('Escape');
  await page.goto('./#/settings');
  await page.screenshot({ path: `${OUT}/9-settings.png`, fullPage: true });
  await page.setViewportSize({ width: 1280, height: 800 });
  await page.goto('./#/');
  await page.locator('a', { hasText: "Ananya's wedding" }).first().click();
  await page.locator('.fn-card', { hasText: 'Mehendi' }).click();
  await page.screenshot({ path: `${OUT}/10-desktop.png` });
});
